parameters:
    bc_user_admin.menu_builder.class: Bc\Bundle\UserBundle\Menu\Builder

services:
    bc_user_admin.menu_builder:
        class: %bc_user_admin.menu_builder.class%
        arguments:
            - @knp_menu.factory
            - @translator

    bc_user_admin.menu.user_admin:
        class: Knp\Menu\MenuItem
        factory_service: bc_user_admin.menu_builder
        factory_method: createUserAdminMenu
        tags:
            - { name: knp_menu.menu, alias: user_admin }
